### ISSUE TITLE
Unselecting all User Roles causes all to be selected

### ISSUE THREAD

**Issue by grahamarmfield** [boswall/Content-Author-Accessibility-Preview#1]
When the plugin is first activated, no user roles appear to be selected in the settings page.

I can then select one or more and press Save Settings.

Then if I deselect all of them and press Save Settings, all of them are checked.

**Comment by boswall** [comment]
Hmm, yes I wasn't sure what best to do when all the user roles are deselected; that would not show the CSS in any circumstance. What do feel would be the best action here? Allow the user to make this error? Show a warning?

I had thought the system would auto select all user roles, but had not tested it properly. Let me investigate.
