### ISSUE TITLE
Settings page - labels for checkboxes

### ISSUE THREAD

**Issue by grahamarmfield** [boswall/Content-Author-Accessibility-Preview#2]
Need to make sure that all the checkboxes in the settings page have attached labels. Nesting the checkbox inside the label is OK but you still need the explicit id/for connection. And the convention for checkboxes is that the label should follow the checkbox.

**Comment by boswall** [comment]
This is a fairly embarrassing oversight given that this is a plugin to highlight accessibility issues. Will add id/for tags.

Need to rethink the options layout. The WordPress Settings API might be limiting but perhaps having the 3 view options grouped together (visually) with their labels following the checkboxes would be better?

**Comment by boswall** [comment]
Would this layout be better?

![image](https://user-images.githubusercontent.com/6197413/49158482-2af1f780-f31a-11e8-9560-011465a310f7.png)

I would also like to add some JS to disable the Preview and Customizer options when Site-wide is checked. Site-wide overrides the other views anyway. This layout might make more sense that these options are related.
