### ISSUE TITLE
Add Link to Settings Options in WP Admin Plugin Overview

### ISSUE THREAD

**Issue by 00travelgirl00** [boswall/Content-Author-Accessibility-Preview#6]
If user install the plugin and looking for the settings options, it would be good to add a link to the settings into the plugin description. 

<img width="1439" alt="Bildschirmfoto 2019-08-01 um 23 51 57" src="https://user-images.githubusercontent.com/21318377/62329922-8e3eb580-b4b7-11e9-8215-508fe94e06e1.png">

**Comment by boswall** [comment]
Great suggestion, thank you.

I'll add a settings link to v1.2

**Comment by boswall** [comment]
I thought I'd added this before. I had but then moved the code to another file, changing the base filename and breaking the code.

Should be fixed now.
